FROM openjdk:23-jdk

WORKDIR /app

COPY /target/wth-app-0.0.1-SNAPSHOT.jar app.jar

#ENV WEATHER_API_KEY=${WEATHER_API_KEY}
#ENV WEATHER_API_URL=${WEATHER_API_URL}
#ENV GEO_API_URL=${GEO_API_URL}
#ENV MAILGUN_API_KEY=${MAILGUN_API_KEY}
#ENV MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
#ENV MAILGUN_EMAIL=${MAILGUN_EMAIL}

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]